// export const fields = [
//   { label: 'Field 1', value: 'field_1' },
//   { label: 'Field 2', value: 'field_2' },
//   { label: 'Field 3', value: 'field_3' },
//   { label: 'Field 4', value: 'field_4' },
// ];
export const fields = [
  {
    label: 'Silo',
    value: 'silo',
  },
  {
    label: 'Conveyor / Gantry Stacker Reclaimer',
    value: 'conveyor',
  },
  {
    label: 'Hopper',
    value: 'hopper',
  },
  {
    label: 'Building (administration), Building (industrial),  Preheater tower',
    value: 'building',
  },
  {
    label: 'Ladder Walkway Staircase Work platform Access platform',
    value: 'platform',
  },
];

export const formFieldConfigs = {
  silo: [
    {
      type: 'dropdown',
      label: 'Stored Material',
      name: 'stored_material',
      size: 12,
      required: true,
      options: [
        'Homo material',
        'Additives',
        'Clinker',
        'Cement',
        'Solid Fuels',
        'Finished products',
        'Liquid Fuels',
      ],
    },
    {
      type: 'toggle',
      label: 'Original wall thickness is known?',
      name: 'thickness',
      size: 12,
      required: true,
      condition: {
        fieldName: 'thickness',
        value: true,
        fields: [
          {
            type: 'input',
            label: 'Original wall thickness',
            name: 'wall_thickness',
            inputType: 'number',
            size: 6,
            required: true,
          },
          {
            type: 'dropdown',
            label: 'Units',
            name: 'units',
            options: ['inches', 'mm'],
            size: 6,
            required: true,
          },
        ],
      },
    },
  ],
  building: [
    {
      type: 'dropdown',
      label: 'Building type',
      name: 'buildingType',
      size: 12,
      required: true,
      options: [
        'Industrial',
        'Administration',
        'Storage',
        'Electrical',
        'Preheater',
      ],
    },
  ],
  platform: [
    {
      type: 'dropdown',
      label: 'Platform type',
      name: 'platformType',
      size: 12,
      required: true,
      options: [
        'Access ramp',
        'Staircase',
        'Walkway',
        'Cat-ladder',
        'Working platform',
      ],
    },
    {
      type: 'dropdown',
      label: 'Location (Floor)',
      name: 'location_floor',
      size: 12,
      required: true,
      options: [
        'Ground',
        '1st Floor',
        '2nd Floor',
        '3rd Floor',
        '4th Floor',
        '5th Floor',
        '6th Floor',
        '7th Floor',
        '8th Floor',
        '9th Floor',
        '10th Floor',
      ],
    },
    {
      type: 'dropdown',
      label: 'Surface type',
      name: 'surfaceType',
      size: 12,
      required: true,
      options: ['Grating', 'Checker plate', 'Concrete', 'Composite'],
    },
    {
      type: 'toggle',
      label: 'Inspection colour coded or tagged?',
      name: 'color_tagged',
      size: 12,
      required: true,
    },
  ],
  conveyor: [
    {
      type: 'dropdown',
      label: 'Type of support',
      name: 'supportType',
      size: 12,
      required: true,
      options: ['Colums / legs', 'Suspended', 'Cantilever', 'encastred'],
    },
    {
      type: 'dropdown',
      label: 'Sliding or bearing  joints/supports are located and accesible?',
      name: 'sliding_or_bearing',
      size: 12,
      required: true,
      options: ['Yes', 'No', 'Non Applicable'],
    },
    {
      type: 'dropdown',
      label: 'Fixed or Mobile structure?',
      name: 'structure_type',
      size: 12,
      required: true,
      options: ['Fixed', 'Mobile'],
    },
  ],
  hopper: [
    {
      type: 'dropdown',
      label: 'Type of support',
      name: 'supportType',
      size: 12,
      required: true,
      options: ['Suspended', 'Supported by foot or other structure'],
    },
    {
      type: 'radio',
      label: 'Fixation type',
      name: 'fixationType',
      size: 12,
      required: true,
      options: ['Bolted', 'Welded', 'Non Applicable'],
    },
    {
      type: 'toggle',
      label: 'Original wall thickness is known?',
      name: 'wallThicknessStatus',
      size: 12,
      required: true,
      options: ['yes', 'no'],
      condition: {
        fieldName: 'wallThicknessStatus',
        value: true,
        fields: [
          {
            type: 'input',
            label: 'Original wall thickness',
            name: 'wallThickness',
            inputType: 'number',
            size: 12,
            required: true,
          },
        ],
      },
    },
  ],
};
